Input Formular for Query edited
karrycgi/next-learn pull request #4
Opened 2022-01-25 14:59 UTC by AdrianAtCgi

Input Formular for Query edited

2022-01-26 09:15 UTC, karrycgi requested changes
Formulare verfügen typischerweise nur über Logik im Input jedoch führen sie selber keine Suche oder ähnliches aus. die typischen Props für diese Aufgabe wären:

interface Props {
    value: RedNoticeQuery,
    onChange: (value:RedNoticeQuery) => void
}

2022-01-27 08:00 UTC, AdrianAtCgi commented
> Verbesserung durchgeführt

2022-01-31 09:23 UTC, AdrianAtCgi commented
React Thinking: Atomisierung der Komponenten vorgenommen

2022-01-31 09:25 UTC, AdrianAtCgi commented
lgtm

2022-01-31 09:25 UTC, merged