Drei Spalten + Banner -  Noch ohne Array
karrycgi/next-learn pull request #6
Opened 2022-01-26 09:24 UTC by vukovicbo

Please review and merge....

2022-01-26 09:27 UTC, karrycgi requested changes

2022-01-26 09:27 UTC, karrycgi commented on components/BannerComponent.component.tsx
> +        <p>
Warum ein p-tag? Hier sind doch keine Absätze im Sinne eines Textes?

2022-01-26 09:29 UTC, vukovicbo commented on components/BannerComponent.component.tsx
> +        <p>
...mangelndes Frontend-Know-How :-)

2022-01-26 10:54 UTC, karrycgi commented on components/BannerComponent.component.tsx
> +        <p>
Passiert ;)

2022-01-31 09:17 UTC, AdrianAtCgi commented
lgtm

2022-01-31 09:18 UTC, merged